### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by napelvs** [openmainframeproject-internship/resources#15]
The following links are broken: 
- "Midterm Evaluation for Mentor"
- "Midterm Evaluation for Mentee"
- "Final Evaluation for Mentor"
- "Final Evaluation for Mentee"
- "Mentor Guide"

Could this be fixed?

**Comment by HeroicHitesh** [comment]
The link to [Dynamic CPU support for s390x in OpenBLAS](https://github.com/openmainframeproject-internship/resources/blob/master/proposed_projects/Dynamic%20CPU%20support%20for%20s390x%20in%20OpenBLAS.md) is also broken [here](https://github.com/openmainframeproject-internship/resources/blob/master/proposed.md#available-projects-for-mentees). I can help resolve this issue.

**Comment by HeroicHitesh** [comment]
> The following links are broken:
> 
> * "Midterm Evaluation for Mentor"
> * "Midterm Evaluation for Mentee"
> * "Final Evaluation for Mentor"
> * "Final Evaluation for Mentee"
> * "Mentor Guide"
> 
> Could this be fixed?

These links are broken [here](https://github.com/openmainframeproject-internship/resources/blob/master/README.md#resources)

**Comment by jmertic** [comment]
Fixed now - thank you @HeroicHitesh
